export {getCategories} from './getCategories'
export {getPosts} from './getPosts'
export {getRecentPosts} from './getRecentPosts'
export {getSimilarPosts} from './getSimilarPosts'
export {getPostDetails} from './getPostDetails'
export {submitComment} from './submitComment'
export {getComments} from './getComments'
export {getCategoryDetails} from './getCategoryDetails'
